export const ACTIVATE_FOCUS = 'ACTIVATE_FOCUS'
export const DEACTIVATE_FOCUS = 'DEACTIVATE_FOCUS'

export const CREATE_SEGMENT = 'CREATE_SEGMENT'
export const UPDATE_SEGMENT = 'UPDATE_SEGMENT'
export const DELETE_SEGMENT = 'DELETE_SEGMENT'
